<?php

namespace AirlinePassengerManifest\AirlineCompanies;

abstract class AirlineCompanyAbstract
{
    private $headquarters;
    private $carrierName;
    private $config;

    public function __construct()
    {
        $this->setHeadquarters($this->headquarters); // TODO: Change the autogenerated stub
        $this->setCarrierName($this->carrierName); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * @param mixed $config
     * @return AirlineCompanyAbstract
     */
    public function setConfig($config)
    {
        $this->config = $config;
        return $this;
    }


    /**
     * @param mixed $carrierName
     * @return AirlineCompanyAbstract
     */
    public function setCarrierName($carrierName)
    {
        $this->carrierName = $carrierName;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCarrierName()
    {
        return $this->carrierName;
    }

    /**
     * @return null
     */
    public function getHeadquarters()
    {
        return $this->headquarters;
    }

    /**
     * @param null $headquarters
     * @return AirlineCompanyAbstract
     */
    public function setHeadquarters($headquarters)
    {
        $this->headquarters = $headquarters;
        return $this;
    }


}
