<?php


namespace AirlinePassengerManifest\AirlineCompanies;


class SingaporeAirlineCompany extends AirlineCompanyAbstract
{
    public function __construct()
    {
        parent::setHeadquarters('Singapore'); // TODO: Change the autogenerated stub
        parent::setCarrierName('Singapore Airlines'); // TODO: Change the autogenerated stub
    }
}
