<?php


namespace Plane\AirlineCompanies;


class EmiratesAirlineCompany extends AirlineCompanyAbstract
{

    public function __construct()
    {
        parent::setHeadquarters('UAE'); // TODO: Change the autogenerated stub
        parent::setCarrierName('Emirates'); // TODO: Change the autogenerated stub
    }
}
