<?php


namespace Plane\AirlineCompanies;


class QantasAirlineCompany extends AirlineCompanyAbstract
{

    public function __construct()
    {
        parent::setHeadquarters('Australia'); // TODO: Change the autogenerated stub
        parent::setCarrierName('Qantas'); // TODO: Change the autogenerated stub
    }
}
